default: styles/application.scss
idolmaster: styles/idolmaster.scss
765pro-allstars: styles/765pro-allstars.scss
cinderella: styles/cinderella.scss
millionlive: styles/millionlive.scss
sidem: styles/sidem.scss
shinycolors: styles/shinycolors.scss
gakumas: styles/gakumas.scss
va-liv: styles/va-liv.scss
