name: imastodon Deploy

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to deploy (e.g. imastodon-20260309)'
        required: true

jobs:
  pre-deploy-migrate:
    name: Pre-deploy migration
    uses: ./.github/workflows/imastodon-ecspresso-run-db-migrate.yml
    with:
      image_tag: ${{ inputs.image_tag }}
      skip_post_deployment_migrations: true

  deploy-sidekiq:
    name: Deploy sidekiq
    needs: pre-deploy-migrate
    uses: ./.github/workflows/imastodon-ecspresso-deploy-sidekiq.yml
    with:
      image_tag: ${{ inputs.image_tag }}

  deploy-webapp:
    name: Deploy webapp
    needs: pre-deploy-migrate
    uses: ./.github/workflows/imastodon-ecspresso-deploy-webapp.yml
    with:
      image_tag: ${{ inputs.image_tag }}

  post-deploy-migrate:
    name: Post-deploy migration
    needs:
      - deploy-sidekiq
      - deploy-webapp
    uses: ./.github/workflows/imastodon-ecspresso-run-db-migrate.yml
    with:
      image_tag: ${{ inputs.image_tag }}
      skip_post_deployment_migrations: false
